// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTrello.Data.Contexts;

#nullable disable

namespace MyTrello.Data.Migrations
{
    [DbContext(typeof(SQLiteContext))]
    partial class SQLiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("MyTrello.Data.Entities.Board", b =>
                {
                    b.Property<Guid>("BoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("BoardId")
                        .HasName("PRIMARY");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Boards", (string)null);
                });

            modelBuilder.Entity("MyTrello.Data.Entities.Task", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskListId")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TaskListId" }, "Task_to_TaskList_FK_idx");

                    b.HasIndex(new[] { "Info", "TaskListId" }, "Unique_Task_in_TaskList")
                        .IsUnique();

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("MyTrello.Data.Entities.TaskList", b =>
                {
                    b.Property<Guid>("TaskListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("TaskListId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BoardId" }, "TaskList_to_Board_FK_idx");

                    b.HasIndex(new[] { "BoardId", "Name" }, "Unique_TaskList_in_Board")
                        .IsUnique();

                    b.ToTable("TaskLists", (string)null);
                });

            modelBuilder.Entity("MyTrello.Data.Entities.Task", b =>
                {
                    b.HasOne("MyTrello.Data.Entities.TaskList", "TaskList")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Task_to_TaskList_FK");

                    b.Navigation("TaskList");
                });

            modelBuilder.Entity("MyTrello.Data.Entities.TaskList", b =>
                {
                    b.HasOne("MyTrello.Data.Entities.Board", "Board")
                        .WithMany("TaskLists")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TaskList_to_Board_FK");

                    b.Navigation("Board");
                });

            modelBuilder.Entity("MyTrello.Data.Entities.Board", b =>
                {
                    b.Navigation("TaskLists");
                });

            modelBuilder.Entity("MyTrello.Data.Entities.TaskList", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
